### ISSUE TITLE
requests: complete the repo and add namelists

### ISSUE THREAD

**Issue by mo0zi** [pgierz/simulation_monitoring#1]
Hi Paul

Thanks for the great tool. Here are two requests that come into my mind:

1. Complete repo: could you add the `script` from your confluence document into this repo so that everything needed is here?
2. Add namelists: I would like to have one "namelist" for every model experiment I'm going to monitor with your tool. Something like:
```
esm_exp_dir=/work/expname/
esm_models=(echam fesom)
esm_echam_vars=(echam_var1 echam_var2)
esm_fesom_vars=(fesom_var1)
```
Actually, in my view, it would be great if the `script` works automatically without further editing just based on the "namelist" provided by the user.

Thanks!

**Comment by pgierz** [comment]
"make it better"

....ok.

**Comment by pgierz** [comment]
done; you have a yaml file now that configures what you want to monitor
